name: Packer CI

on:
  push:
    branches:
      - "master"
      - "develop"
      - "release/**"
      - "feature/**"
  pull_request:
    branches: 
      - "master"
      - "staging"
  workflow_dispatch:

jobs:
  hcp-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"
      - name: Run `packer init`
        id: init
        run: "packer init ."
      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
